#!/bin/bash

#Output colors
NORMAL="\033[0;39m"
RED="\033[1;31m"
BLUE="\033[1;34m"

function log() {
  printf "$BLUE ${BORG_ARCHIVE} > $1 $NORMAL\n" $2
}

function error() {
  printf "\n$RED ${BORG_ARCHIVE} >>> ERROR - $1$NORMAL\n" $2
}

function volume_snap() {
  VOLUME_SNAP=$(docker volume create -d lvm --opt snapshot=$1 --opt --thinpool=${LVM_THIN} $1_snap)
  log "Volume snapshot '${VOLUME_SNAP}' for ${VOLUME} created."
}

function volume_unsnap() {
  VOLUME_SNAP=$(docker volume remove $1_snap)
  log "Volume snapshot '${VOLUME_SNAP}' removed."
}

function volumes_backup() {
  log "Backup Volumes: '${LVM_VOLUMES[*]}'"

  for VOLUME in ${LVM_VOLUMES[@]}
  do
    BACKUP_VOLUMES="${BACKUP_VOLUMES} --mount src=${VOLUME}_snap,target=/borg/data/${BORG_ARCHIVE}/${VOLUME/${BORG_ARCHIVE}_/},volume-opt=nouuid,ro"
  done

  docker run --rm \
    -e BORG_RELOCATED_REPO_ACCESS_IS_OK=yes \
    -e BORG_REPO="ssh://${SSH_USER}@${SSH_HOST}:23/./${SSH_PATH}" \
    -e BORG_PASSCOMMAND="cat /borg/.borg-passphrase" \
    -e ARCHIVE="${BORG_ARCHIVE}-{now:%Y-%m-%d}" \
    -e PRUNE_PREFIX="${BORG_ARCHIVE}-" \
    ${BACKUP_VOLUMES} \
    -v ${PASSPHRASE}:/borg/.borg-passphrase:ro \
    -v ${BORG_CACHE}:/borg/cache \
    -v ${BORG_CONFIG}:/borg/config \
    -v ${BORG_KEYS}:/borg/config/keys \
    borg-backup

  return $?
}

function backup() {
  for VOLUME in ${LVM_VOLUMES[@]}
  do
    volume_snap ${VOLUME}
  done

  volumes_backup
  DOCKER_RETURN=$?

  for VOLUME in ${LVM_VOLUMES[@]}
  do
    volume_unsnap ${VOLUME}
  done

  return ${DOCKER_RETURN}
}


function arguments() {
  while getopts ":v:volume:a:archive:c:check:" opt;
  do
    case "${opt}"
      in
      v|volume) LVM_VOLUMES=( "${LVM_VOLUMES[@]}" "${OPTARG}" ); ;;
      a|archive) BORG_ARCHIVE=${OPTARG};;
      c|check) BORG_CHECK=true;;
    esac
  done
}

arguments "$@"
backup
exit
